[build]
base = "frontend"
command = "yarn build"
publish = "dist"  # ✅ <- was "frontend/dist", now just "dist"

[build.environment]
NODE_VERSION = "18"
EXPO_CLI_VERSION = "6.3.1"

[build.cache]
  paths = ["node_modules"]
